### ISSUE TITLE
Slack Notifications

### ISSUE THREAD

**Issue by leandrok** [dbschenker/node-undertaker#4]
Hello, congratulations for this great service
Can you add the ability of sending Slack notifications please?

**Comment by camaeel** [comment]
@leandrok 
Thanks.

Although we don't need such notifications internally it may make sense to have notifications. 
I'm hesitating if those should go to "slack-compatible" http webhook or some notification service like SNS. SNS might be more robust than simple http request, on the other hand SNS will be cloud provider specific and node-undertaker is designed to be able to handle nodes running using other infrastructure providers (for now only AWS is implemented). 

As a quick workaround and temporary solution, you can try monitoring events that are created after every action taken by node-undertaker. Kube-state-metrics or some event exporters can be helpful.

**Comment by leandrok** [comment]
Thanks for your feedback. Yes, SNS can be a good option so users have the flexibility of sending the alerts to different targets (email, Slack, webhook) through SNS.. I'll check the metrics export approach. Thanks.

**Comment by leandrok** [comment]
Perfect thanks!

**Comment by camaeel** [comment]
I updated information about metric that exports node statuses observed.

**Comment by camaeel** [comment]
Released with v1.1.0
